---
version: '3'
services:
  freqtradePMAX_TEST:
    image: mk/ft:latest
    restart: unless-stopped
    container_name: CntPMAX_TEST
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "0.0.0.0:8081:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_rsi_auto_pmax.log
      --db-url sqlite:////freqtrade/user_data/tradesv3_auto_pmax.sqlite
      --config /freqtrade/user_data/configs/configPMAX.json
      --strategy MKPmaxDcaStrategyV1_0


networks:
  default:
    external:
      name: proxy_default
